import { useCallback, useEffect, useRef, useState } from 'react'
import { Activity, ArrowDownToLine, ArrowRight, Bell, Check, ChevronRight, Clock3, FlaskConical, HeartPulse, Info, LayoutDashboard, Pause, Play, Plus, RotateCcw, Search, ShieldCheck, SlidersHorizontal, StepForward, Users, Wifi, X } from 'lucide-react'
import type { Evaluation, Observation, Patient, Twin } from './types'
import { Badge, Contributions, HeartVisual, Loading, Logo, percent, riskClass, SignalCard, TrendChart, TwinIndices } from './components'

async function api<T>(path:string,body?:unknown,signal?:AbortSignal):Promise<T> {
  const response=await fetch(`/api${path}`, {signal, ...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})})
  const result=await response.json()
  if(!response.ok) throw new Error(typeof result.detail==='string'?result.detail:'Please check the supported input ranges and date.')
  return result as T
}

const scenarioDefaults={weight_delta:0,heart_rate_delta:0,respiratory_rate_delta:0,activity_percent:0}
const sliderSpecs=[{key:'weight_delta',label:'Weight change',min:-3,max:5,step:.1,unit:'kg'}, {key:'heart_rate_delta',label:'Resting heart rate',min:-15,max:25,step:1,unit:'bpm'}, {key:'respiratory_rate_delta',label:'Respiratory rate',min:-3,max:8,step:.5,unit:'/min'}, {key:'activity_percent',label:'Daily activity',min:-80,max:50,step:5,unit:'%'}] as const

export default function App() {
  const [page,setPage]=useState<'population'|'patient'|'evaluation'|'research'>('population')
  const [patients,setPatients]=useState<Patient[]>([]), [selected,setSelected]=useState('')
  const [detail,setDetail]=useState<{patient:Patient;twin:Twin}|null>(null), [rows,setRows]=useState<Observation[]>([])
  const [evaluation,setEvaluation]=useState<Evaluation|null>(null), [day,setDay]=useState(35)
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false)
  const [error,setError]=useState(''),[notice,setNotice]=useState(''), [search,setSearch]=useState(''),[filter,setFilter]=useState('All patients')
  const [signal,setSignal]=useState('risk'),[tab,setTab]=useState('Overview'),[modal,setModal]=useState<'scenario'|'telemetry'|'reset'|null>(null)
  const [scenario,setScenario]=useState({...scenarioDefaults}),[simulated,setSimulated]=useState<Twin|null>(null)
  const [telemetry,setTelemetry]=useState<Record<string,string>>({}), [revision,setRevision]=useState(0)
  const actionLock=useRef(false)
  const loadPopulation=useCallback(async()=>{
    const result=await api<{patients:Patient[];replay_day:number}>('/patients')
    setPatients(result.patients);setDay(result.replay_day);setSelected(old=>old||result.patients[0]?.patient_id||'');setRevision(r=>r+1)
  },[])
  useEffect(()=>{loadPopulation().catch(e=>setError(e.message)).finally(()=>setLoading(false));api<Evaluation>('/evaluation').then(setEvaluation).catch(e=>setError(e.message))},[loadPopulation])
  useEffect(()=>{
    if(!selected)return
    const controller=new AbortController()
    setSimulated(null)
    Promise.all([api<{patient:Patient;twin:Twin}>(`/patients/${selected}`,undefined,controller.signal),api<{observations:Observation[]}>(`/patients/${selected}/timeline`,undefined,controller.signal)])
      .then(([result,timeline])=>{setDetail(result);setRows(timeline.observations)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)})
    return ()=>controller.abort()
  },[selected,revision])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer)},[notice])
  useEffect(()=>{
    if(!modal)return
    const previous=document.activeElement as HTMLElement|null
    const dialog=document.querySelector<HTMLElement>('[role="dialog"]')
    const getFocusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),a[href]')??[])
    getFocusable()[0]?.focus()
    const handle=(event:KeyboardEvent)=>{
      if(event.key==='Escape'&&!busy){setModal(null);return}
      if(event.key!=='Tab')return
      const elements=getFocusable(),first=elements[0],last=elements.at(-1)
      if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}
      else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}
    }
    document.addEventListener('keydown',handle)
    return()=>{document.removeEventListener('keydown',handle);previous?.focus()}
  },[modal,busy])
  const advance=useCallback(async()=>{
    if(actionLock.current)return
    actionLock.current=true;setBusy(true);setError('')
    try{const result=await api<{day:number;updated:number;finished:boolean}>('/demo/advance',{});await loadPopulation();if(result.finished){setPlaying(false);setNotice('Replay complete. Reset the demo to start again.')}else if(!result.updated){setNotice('No new readings available for this replay day.')}}
    catch(e){setError((e as Error).message);setPlaying(false)}finally{actionLock.current=false;setBusy(false)}
  },[loadPopulation])
  useEffect(()=>{if(!playing||busy)return;const timer=setTimeout(()=>void advance(),2400);return()=>clearTimeout(timer)},[playing,busy,advance])
  const focus=(pid:string)=>{if(pid!==selected)setDetail(null);setSelected(pid);setPage('patient');setSignal('risk');setTab('Overview')}
  const openModal=(kind:'scenario'|'telemetry'|'reset')=>{
    setPlaying(false);setError('');setModal(kind)
    if(kind==='scenario'){setScenario({...scenarioDefaults});setSimulated(null)}
    if(kind==='telemetry'&&detail){const date=new Date(`${detail.twin.timestamp}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+1);setTelemetry({timestamp:date.toISOString().slice(0,10),...Object.fromEntries(detail.twin.signals.map(s=>[s.key,s.value===null?'':String(s.value)]))})}
  }
  const reset=async()=>{setBusy(true);setError('');try{await api('/demo/reset',{});setSelected('');setDetail(null);await loadPopulation();setModal(null);setNotice('Demo reset to day 35.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const runScenario=async()=>{setBusy(true);setError('');try{const result=await api<{simulated:Twin}>(`/patients/${selected}/simulate`,scenario);setSimulated(result.simulated)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const ingest=async()=>{setBusy(true);setError('');try{const payload=Object.fromEntries(Object.entries(telemetry).map(([k,v])=>[k,k==='timestamp'?v:v===''?null:Number(v)]));await api(`/patients/${selected}/telemetry`,payload);await loadPopulation();setModal(null);setNotice('Daily reading saved. Patient twin updated.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const download=()=>{const blob=new Blob([JSON.stringify({patient:detail?.patient,twin:detail?.twin,observations:rows,synthetic:true},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${selected}-synthetic-twin.json`;link.click();URL.revokeObjectURL(url)}
  const high=patients.filter(p=>p.status==='High risk').length,watch=patients.filter(p=>p.status==='Watch').length,stable=patients.filter(p=>p.status==='Stable').length
  const filtered=patients.filter(p=>(filter==='All patients'||p.status===filter)&&`${p.patient_id} ${p.name} ${p.hf_type}`.toLowerCase().includes(search.toLowerCase()))
  const twin=detail?.twin,patient=detail?.patient
  const chosenSignal=twin?.signals.find(s=>s.key===signal)
  const model=evaluation?.models.find(m=>m.name==='Personalized CardioTwin')

  return <div className="app-shell">
    <aside className="sidebar"><Logo/><div className="workspace-label">CLINICIAN WORKSPACE</div>
      <nav aria-label="Main navigation">{[{key:'population',label:'Patient overview',icon:LayoutDashboard},{key:'patient',label:'Digital twin',icon:HeartPulse},{key:'evaluation',label:'Model performance',icon:Activity},{key:'research',label:'Research & methods',icon:FlaskConical}].map(item=><button key={item.key} className={page===item.key?'nav-item active':'nav-item'} onClick={()=>setPage(item.key as typeof page)}><item.icon size={19}/>{item.label}{page===item.key&&<ChevronRight size={15}/>}</button>)}</nav>
      <div className="sidebar-note"><div><FlaskConical size={19}/><b>Built for discovery.</b></div><p>A living patient model.<br/>An earlier signal of change.</p><span>SYNTHETIC DATA DEMO</span></div>
      <div className="sidebar-bottom"><div className="avatar">CT</div><div>Research workspace<small>CardioTwin-HF · v0.1</small></div><ShieldCheck size={17}/></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={13}/><span>{page==='population'?'Patient overview':page==='patient'?'Digital twin':page==='evaluation'?'Model performance':'Research & methods'}</span></div><div className="topbar-right"><span className="connection"><i/>{patients.length?'API connected':'Connecting to API'}</span><span className="demo-pill"><FlaskConical size={13}/> Research demo</span><div className="profile">CT</div></div></header>
      <div className="content">
        <div className="research-banner"><Info size={15}/><span>All patients and readings are synthetic. Risk estimates demonstrate the prototype and are not clinically validated.</span><a href="/docs" target="_blank" rel="noreferrer">API docs <ArrowUpRightIcon/></a></div>
        {error&&<div className="error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
        {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
        {loading?<Loading/>:<>
        <div className="page-heading"><div><span className="eyebrow">{page==='population'?'CONTINUOUS CARE, PERSONALIZED':page==='patient'?'THE PATIENT BEHIND THE SIGNAL':page==='evaluation'?'MEASURED, NOT ASSUMED':'FROM RESEARCH TO PROTOTYPE'}</span><h1>{page==='population'?'A clearer picture. An earlier signal.':page==='patient'?'Your patient’s living twin.':page==='evaluation'?'Evidence behind the model.':'A thoughtful foundation.'}</h1><p>{page==='population'?'See who is changing, understand why, and explore their personal trajectory.':page==='patient'?'Historical context meets daily physiology in one evolving patient model.':page==='evaluation'?'Honest comparisons on entirely held-out synthetic patients.':'The principles, assumptions, and boundaries of CardioTwin-HF.'}</p></div>{page==='patient'?<button className="button secondary" onClick={download} disabled={!detail}><ArrowDownToLine size={16}/>Export twin</button>:<div className="day-chip"><Clock3 size={15}/>Replay day <b>{day}</b></div>}</div>
        {(page==='population'||page==='patient')&&<div className="replay-bar"><div><span className="live-dot"/><b>Wearable replay</b><span>One click advances one daily observation</span></div><div><button className="button text" disabled={busy} onClick={()=>openModal('reset')}><RotateCcw size={14}/>Reset</button><button className="button secondary small-btn" onClick={()=>void advance()} disabled={busy||day>=60}><StepForward size={14}/>Next day</button><button className={`button primary small-btn ${playing?'playing':''}`} onClick={()=>setPlaying(p=>!p)} disabled={day>=60||busy}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?'Pause replay':'Play replay'}</button></div></div>}

        {page==='population'&&<>
          <div className="stats-grid"><SummaryCard icon={<Users size={20}/>} label="Monitored patients" number={patients.length} detail="Fictional patient cohort"/><SummaryCard icon={<Bell size={20}/>} label="High risk" number={high} detail="Estimated risk ≥ 60%" tone="coral"/><SummaryCard icon={<Clock3 size={20}/>} label="Watch closely" number={watch} detail="Estimated risk 20–60%" tone="amber"/><SummaryCard icon={<ShieldCheck size={20}/>} label="Stable signal" number={stable} detail="Estimated risk < 20%" tone="green"/></div>
          <div className="overview-grid"><section className="card patient-list"><div className="card-heading"><div><h2>Patient priority queue <span className="count">{patients.length}</span></h2><p>Sorted by estimated 7-day risk</p></div><span className="subtle-tag"><Wifi size={12}/>Daily readings</span></div>
            <div className="table-tools"><label className="search"><Search size={16}/><input aria-label="Search patients" placeholder="Search patient ID or phenotype…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter risk category" value={filter} onChange={e=>setFilter(e.target.value)}>{['All patients','High risk','Watch','Stable','Insufficient data'].map(s=><option key={s}>{s}</option>)}</select></div>
            <div className="table-scroll"><table className="patient-table"><thead><tr><th>Patient</th><th>7-day risk</th><th>Status</th><th>Data coverage</th><th aria-label="Open patient"/></tr></thead><tbody>{filtered.map(p=><tr key={p.patient_id} className={selected===p.patient_id?'selected':''}><td><button className="patient-link" onClick={()=>focus(p.patient_id)}><span className="patient-avatar">{p.patient_id.slice(-2)}</span><span><b>{p.patient_id}</b><small>{p.age}y · {p.sex} · {p.hf_type}</small></span></button></td><td><div className={`table-risk ${riskClass(p.status)}`}><b>{percent(p.risk)}</b><div><i style={{width:`${(p.risk??0)*100}%`}}/></div></div></td><td><Badge status={p.status}/></td><td><span className="coverage"><span style={{background:p.coverage>=.8?'#7c9e86':'#c09156'}}/>{Math.round(p.coverage*100)}%</span><small className="reading-date">{p.timestamp}</small></td><td><button className="icon-button" aria-label={`Open ${p.patient_id} twin`} onClick={()=>focus(p.patient_id)}><ChevronRight size={16}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No patients match this search.</div>}</div><div className="table-footer">Showing {filtered.length} of {patients.length} patients <span>Entirely synthetic · patient-specific baselines</span></div>
          </section><aside className="overview-aside"><section className="card featured-twin"><div className="card-heading"><div><span className="eyebrow">CURRENT FOCUS</span><h2>{selected||'Patient twin'}</h2></div><HeartPulse size={20} className="text-coral"/></div><HeartVisual twin={twin} small/>{twin&&<><div className="featured-risk"><div><small>7-day estimated risk</small><strong className={riskClass(twin.status)}>{percent(twin.risk?.probability)}</strong></div><Badge status={twin.status}/></div><p className="feature-description">An individual baseline. A daily update. A clearer view of physiological change.</p><button className="button primary full" onClick={()=>focus(selected)}>Explore digital twin <ArrowRight size={16}/></button></>}</section><section className="insight-card"><div className="insight-icon"><FlaskConical size={20}/></div><h3>Same number.<br/>Different meaning.</h3><p>A resting pulse of 75 bpm means more when a patient’s usual pulse is 58 than when it is 73.</p><button onClick={()=>setPage('research')}>How personalization works <ArrowRight size={14}/></button></section></aside></div>
        </>}

        {page==='patient'&&(detail?<>
          <div className="patient-header"><div className="patient-identity"><div className="patient-avatar large">{selected.slice(-2)}</div><div><h2>{selected} <span>Fictional patient</span></h2><p>{patient?.age} years · {patient?.sex} · {patient?.hf_type} · NYHA {patient?.nyha}</p></div></div><div><label className="sr-only" htmlFor="patient-selector">Choose a patient</label><select id="patient-selector" value={selected} onChange={e=>{setSelected(e.target.value);setDetail(null)}}>{patients.map(p=><option key={p.patient_id} value={p.patient_id}>{p.patient_id} · {p.status}</option>)}</select><button className="button secondary" onClick={()=>openModal('telemetry')} disabled={!twin?.timestamp}><Plus size={16}/>Add daily reading</button></div></div>
          <div className="patient-tabs" role="tablist">{['Overview','Explainability','EHR profile','Data timeline'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}</button>)}</div>
          {tab==='Overview'&&twin&&<>
            <div className="patient-top-grid"><section className="card risk-card"><div><span className="eyebrow">ESTIMATED 7-DAY DECOMPENSATION RISK</span><div className="risk-score"><strong className={riskClass(twin.status)}>{percent(twin.risk?.probability)}</strong><Badge status={twin.status}/></div><p>Personal baseline + wearable trends + EHR context</p><div className="risk-scale"><i style={{left:`${(twin.risk?.probability??0)*100}%`}}/></div><div className="risk-scale-labels"><span>Stable</span><span>Watch</span><span>High risk</span></div><div className="data-note"><Wifi size={14}/> {Math.round(twin.quality.coverage*100)}% sensor coverage <span>·</span> Updated {twin.timestamp}</div><button className="button secondary" onClick={()=>openModal('scenario')} disabled={!twin.risk}><SlidersHorizontal size={15}/>Explore a scenario</button></div><HeartVisual twin={twin}/></section><section className="card state-card"><div className="card-heading"><div><h2>Digital twin state</h2><p>Model-derived indices · 0–100</p></div><Activity size={18}/></div><TwinIndices twin={twin}/><p className="micro-note">Higher burden means greater deviation; higher stability means closer to baseline. These are illustrative indices.</p></section></div>
            <div className="signal-grid">{twin.signals.slice(0,6).map(s=><SignalCard key={s.key} signal={s} active={signal===s.key} onClick={()=>setSignal(s.key)}/>)}</div>
            <div className="patient-bottom-grid"><section className="card trend-card"><div className="card-heading"><div><h2>{signal==='risk'?'Risk trajectory':chosenSignal?.label}</h2><p>{signal==='risk'?'A daily view of the estimated 7-day risk':'Dashed line shows the personal baseline · gaps are missing data'}</p></div><span className="subtle-tag">Last {rows.length} readings</span></div><div className="chart-tabs">{[{key:'risk',label:'Risk'},...twin.signals.map(s=>({key:s.key,label:s.key==='resting_hr'?'Heart rate':s.key==='respiratory_rate'?'Respiration':s.key==='sleep_hours'?'Sleep':s.key==='systolic_bp'?'Systolic BP':s.key==='diastolic_bp'?'Diastolic BP':s.key==='steps'?'Activity':s.label}))].map(s=><button key={s.key} onClick={()=>setSignal(s.key)} className={signal===s.key?'active':''}>{s.label}</button>)}</div><TrendChart rows={rows} signal={signal} baseline={chosenSignal?.baseline} unit={chosenSignal?.unit}/><div className="chart-legend"><i/>{signal==='risk'?'Estimated risk':'Observed signal'}{signal!=='risk'&&<><i className="baseline"/>Personal baseline</>}</div></section><section className="card explanation-card"><div className="card-heading"><div><h2>Why this risk?</h2><p>TreeSHAP · calibrated log-odds</p></div><Info size={16}/></div>{twin.risk?<Contributions values={twin.risk.explanation.contributions}/>:<p>Personal baseline or current data is incomplete.</p>}<button className="button text" onClick={()=>setTab('Explainability')}>View full explanation <ArrowRight size={14}/></button></section></div>
          </>}
          {tab==='Explainability'&&twin&&<section className="card explanation-full"><div className="card-heading"><div><h2>A traceable estimate.</h2><p>Each feature pushes the model’s log-odds higher or lower.</p></div><span className="subtle-tag">Native TreeSHAP</span></div>{twin.risk?<><div className="explanation-summary"><div><small>Base log-odds</small><strong>{twin.risk.explanation.base_value.toFixed(3)}</strong></div><Plus size={16}/><div><small>Sum of contributions</small><strong>{twin.risk.explanation.contributions.reduce((a,b)=>a+b.contribution,0).toFixed(3)}</strong></div><span>=</span><div><small>Final log-odds</small><strong>{twin.risk.explanation.log_odds.toFixed(3)}</strong></div><ArrowRight size={18}/><div><small>After sigmoid</small><strong>{percent(twin.risk.probability)}</strong></div></div><div className="explanation-columns"><Contributions values={twin.risk.explanation.contributions} limit={12}/><div className="method-note"><h3>Read the explanation carefully.</h3><p>Coral contributions increase the model’s estimate. Green contributions lower it. Values are additive in log-odds space, not percentage-point changes in probability.</p><p>The displayed list shows the 12 largest contributions; the sum above includes all features.</p><p>These are predictive associations in synthetic data. They do not establish causation or support treatment decisions.</p></div></div></>:<p>Risk inference is paused until adequate baseline and current readings are available.</p>}</section>}
          {tab==='EHR profile'&&patient&&<section className="card ehr-card"><div className="card-heading"><div><h2>Historical patient context</h2><p>Fictional EHR attributes used by the model</p></div><Badge status="Synthetic EHR"/></div><div className="ehr-grid">{[{label:'Age',value:`${patient.age} years`},{label:'HF phenotype',value:patient.hf_type},{label:'LVEF',value:`${patient.lvef}%`},{label:'NYHA class',value:patient.nyha},{label:'Creatinine',value:`${patient.creatinine} mg/dL`},{label:'eGFR',value:`${patient.egfr} mL/min/1.73m²`},{label:'Sodium',value:`${patient.sodium} mmol/L`},{label:'Hemoglobin',value:`${patient.hemoglobin} g/dL`},{label:'Previous admissions',value:patient.previous_admissions},{label:'Diabetes',value:patient.diabetes?'Yes':'No'},{label:'Chronic kidney disease',value:patient.ckd?'Yes':'No'},{label:'COPD',value:patient.copd?'Yes':'No'}].map(x=><div key={x.label}><small>{x.label}</small><strong>{x.value}</strong></div>)}</div><div className="method-note"><h3>Every patient begins with their own baseline.</h3><p>The first 14 observed days establish a frozen stable-period median and median absolute deviation for each signal. This assumption holds in the simulator and requires verification for any real deployment.</p></div></section>}
          {tab==='Data timeline'&&<section className="card"><div className="card-heading"><div><h2>Daily observation ledger</h2><p>Persisted readings only; withheld replay data is excluded</p></div><button className="button text" onClick={download}><ArrowDownToLine size={15}/>Export JSON</button></div><div className="table-scroll"><table className="patient-table"><thead><tr><th>Date</th><th>Risk</th><th>HR</th><th>HRV</th><th>Weight</th><th>Resp.</th><th>SpO₂</th><th>Steps</th></tr></thead><tbody>{[...rows].reverse().map(row=><tr key={row.day}><td>{row.timestamp}</td><td>{percent(row.risk)}</td>{['resting_hr','hrv','weight','respiratory_rate','spo2','steps'].map(key=><td key={key}>{row[key]??'—'}</td>)}</tr>)}</tbody></table></div></section>}
        </>:<Loading/>)}

        {page==='evaluation'&&evaluation&&<>
          <div className="stats-grid"><SummaryCard icon={<Users size={20}/>} label="Synthetic patients" number={evaluation.n_patients} detail={`${evaluation.n_samples.toLocaleString()} labeled patient-days`}/><SummaryCard icon={<ShieldCheck size={20}/>} label="Held-out test patients" number={evaluation.split_counts.test} detail="No patient overlaps with training" tone="green"/><SummaryCard icon={<Activity size={20}/>} label="Personalized ROC-AUC" number={model?.roc_auc.toFixed(3)??'—'} detail="Discrimination on synthetic data" tone="coral"/><SummaryCard icon={<FlaskConical size={20}/>} label="Personalized PR-AUC" number={model?.pr_auc.toFixed(3)??'—'} detail={`${percent(evaluation.positive_fraction)} positive patient-days overall`} tone="amber"/></div>
          <section className="card"><div className="card-heading"><div><h2>What does personalization add?</h2><p>Training 70% · calibration & threshold selection 15% · untouched test set 15%</p></div><span className="subtle-tag">Seed 2026</span></div><div className="table-scroll"><table className="evaluation-table"><thead><tr><th>Model</th><th>ROC-AUC</th><th>PR-AUC</th><th>Brier ↓</th><th>Sensitivity</th><th>Specificity</th><th>False alerts /<br/>patient-month</th><th>Mean lead<br/>days</th></tr></thead><tbody>{evaluation.models.map(m=><tr key={m.name} className={m.name==='Personalized CardioTwin'?'best-model':''}><td><b>{m.name}</b>{m.name==='Personalized CardioTwin'&&<small>Primary prototype model</small>}</td><td>{m.roc_auc.toFixed(3)}</td><td>{m.pr_auc.toFixed(3)}</td><td>{m.brier.toFixed(3)}</td><td>{percent(m.sensitivity)}</td><td>{percent(m.specificity)}</td><td>{m.false_alerts_per_patient_month.toFixed(2)}</td><td>{m.mean_lead_days?.toFixed(1)??'—'}</td></tr>)}</tbody></table></div><div className="table-footer">Operating thresholds maximize validation F1. Dashboard categories use separate demo thresholds (20% / 60%).</div></section>
          <div className="evaluation-grid"><section className="card"><div className="card-heading"><div><h2>Calibration check</h2><p>Predicted vs observed rates · held-out synthetic data</p></div></div>{model&&<CalibrationChart bins={model.calibration}/>}<p className="micro-note">Quantile bins. Closer to the dashed diagonal means better agreement in this benchmark.</p></section><section className="card limitations"><h2>What this benchmark can tell us</h2><p>The model learns generated trajectories and synthetic event labels. These results demonstrate the software pipeline and the value of personalization within this simulator.</p><p>They cannot establish clinical sensitivity, real-world warning time, improved outcomes, or transportability to a hospital population.</p><div className="split-pills">{Object.entries(evaluation.split_counts).map(([k,v])=><span key={k}>{k}<b>{v}</b></span>)}</div><p className="micro-note">False alerts count the start of each consecutive alert episode on negative-label days. Lead time is measured only within the 7-day target window; undetected events are excluded from its mean.</p></section></div>
        </>}

        {page==='research'&&<>
          <section className="research-hero card"><div><span className="eyebrow">CARDIOTWIN-HF</span><h2>Learn the baseline.<br/>Notice the change.</h2><p>A patient-specific virtual state combines fictional EHR context with daily wearable and home-device signals. The twin updates as observations arrive, estimates seven-day synthetic event risk, and explains the model’s reasoning.</p><div className="subtle-tag"><ShieldCheck size={15}/>Engineering proof of concept</div></div><HeartVisual/></section>
          <div className="research-grid">{[{n:'01',title:'A personal baseline',body:'A 14-day stable window estimates each signal’s median and MAD. Minimum observation counts and scale floors avoid unreliable or exploding deviations.'},{n:'02',title:'Causal temporal features',body:'Current readings, 3- and 7-day means and slopes, variability, missingness, and personal deviations use only observations available at the prediction day.'},{n:'03',title:'An interpretable model',body:'XGBoost learns tabular features. Validation-only sigmoid calibration adjusts its probability scale. Native TreeSHAP attributes calibrated log-odds to input features.'},{n:'04',title:'A living virtual state',body:'Illustrative congestion, stress, oxygenation, activity, and hemodynamic indices evolve with readings. They are derived scores, not measured physiological parameters.'},{n:'05',title:'A scenario, not a prescription',body:'Perturb the latest day’s weight, pulse, respiration, or activity. The scenario recomputes the twin without saving readings or estimating treatment effects.'},{n:'06',title:'Honest data provenance',body:'This release uses an in-house seeded simulator only. It does not include Synthea, PhysioNet, real wearables, hospital EHRs, or mechanistic heart simulation.'}].map(item=><section className="card research-method" key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.body}</p></section>)}</div>
          <section className="card research-references"><h2>Research that informed the concept</h2><p>These studies motivate the design. Their published results are not this prototype’s results.</p><a href="https://pubmed.ncbi.nlm.nih.gov/32093506/" target="_blank" rel="noreferrer"><div><b>LINK-HF · wearable monitoring</b><span>Personalized physiological monitoring for HF hospitalization prediction</span></div><ArrowRight size={17}/></a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11449733/" target="_blank" rel="noreferrer"><div><b>TIM-HF2 · seven-day prediction</b><span>Machine learning with daily remote-monitoring observations</span></div><ArrowRight size={17}/></a><a href="https://www.nature.com/articles/s41746-025-01501-9" target="_blank" rel="noreferrer"><div><b>Mechanistic HF digital twins</b><span>A more physiologically detailed direction for future research</span></div><ArrowRight size={17}/></a></section>
        </>}
        <footer className="footer"><Logo/><span>Research prototype · Synthetic data · No treatment recommendations</span><a href="https://github.com/1shu1iwari-crypto/digital-twin" target="_blank" rel="noreferrer">View repository <ArrowRight size={13}/></a></footer>
        </>}
      </div>
    </main>
    {modal&&<div className="modal-backdrop" onClick={()=>!busy&&setModal(null)}><section className={`modal ${modal==='reset'?'reset-modal':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="Close dialog" disabled={busy} onClick={()=>setModal(null)}><X size={19}/></button>
      <span className="eyebrow">{modal==='scenario'?'PHYSIOLOGICAL EXPLORATION':modal==='telemetry'?'DAILY SENSOR OBSERVATION':'DEMO CONTROLS'}</span><h2 id="modal-title">{modal==='scenario'?'What if the signals change?':modal==='telemetry'?'Add a daily reading.':'Restart the demo?'}</h2>
      <p>{modal==='scenario'?'Adjust the latest day’s physiology to recompute the model estimate.':modal==='telemetry'?`${selected} · Add exactly the next calendar day. Blank sensors stay missing.`:'This replaces all local demo patients and manually added readings with the original synthetic cohort.'}</p>
      {error&&<div className="error" role="alert">{error}</div>}
      {modal==='scenario'&&<><div className="scenario-sliders">{sliderSpecs.map(s=><label key={s.key}><div><b>{s.label}</b><span>{scenario[s.key]>0?'+':''}{scenario[s.key]} {s.unit}</span></div><input type="range" aria-label={s.label} min={s.min} max={s.max} step={s.step} value={scenario[s.key]} onChange={e=>{setScenario(old=>({...old,[s.key]:Number(e.target.value)}));setSimulated(null)}}/></label>)}</div><div className="scenario-comparison"><div><small>Current estimate</small><strong>{percent(twin?.risk?.probability)}</strong></div><ArrowRight size={22}/><div><small>Scenario estimate</small><strong className="text-coral">{simulated?percent(simulated.risk?.probability):'—'}</strong></div></div>{simulated&&<p className="scenario-result" role="status">Scenario recomputed. Change: {((simulated.risk!.probability-twin!.risk!.probability)*100).toFixed(1)} percentage points. Original readings remain unchanged.</p>}<div className="modal-note"><Info size={15}/>This is a one-day input perturbation, not a causal forecast or a treatment recommendation.</div><button className="button primary full" disabled={busy} onClick={()=>void runScenario()}><SlidersHorizontal size={16}/>{busy?'Recomputing…':'Recompute scenario'}</button></>}
      {modal==='telemetry'&&<form onSubmit={e=>{e.preventDefault();void ingest()}}><div className="telemetry-form"><label className="full-field">Date<input type="date" required value={telemetry.timestamp||''} onChange={e=>setTelemetry(old=>({...old,timestamp:e.target.value}))}/></label>{twin?.signals.map(s=><label key={s.key}>{s.label} <small>({s.unit})</small><input type="number" step="any" aria-label={`${s.label} reading`} value={telemetry[s.key]??''} onChange={e=>setTelemetry(old=>({...old,[s.key]:e.target.value}))} placeholder="Missing"/></label>)}</div><div className="modal-note"><Info size={15}/>Supported ranges validate simulator inputs. Use fictional data only.</div><button className="button primary full" disabled={busy} type="submit"><Plus size={16}/>{busy?'Saving…':'Save reading & update twin'}</button></form>}
      {modal==='reset'&&<div className="reset-buttons"><button className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={()=>void reset()}><RotateCcw size={15}/>{busy?'Resetting…':'Reset demo'}</button></div>}
    </section></div>}
  </div>
}

function ArrowUpRightIcon(){return <ArrowRight size={13}/>}
function SummaryCard({icon,label,number,detail,tone='neutral'}:{icon:React.ReactNode;label:string;number:string|number;detail:string;tone?:string}) {return <section className={`summary-card ${tone}`}><div className="summary-top"><span>{label}</span><i>{icon}</i></div><strong>{number}</strong><p>{detail}</p></section>}
function CalibrationChart({bins}:{bins:{predicted:number;observed:number}[]}) {const x=(v:number)=>40+v*350,y=(v:number)=>230-v*200;return <svg className="calibration-chart" viewBox="0 0 420 270" role="img" aria-label="Calibration curve: predicted probability versus observed event fraction"><line x1={40} y1={230} x2={390} y2={30} stroke="#acb7ac" strokeDasharray="5 5"/>{[0,.25,.5,.75,1].map(t=><g key={t}><line x1={40} y1={y(t)} x2={390} y2={y(t)} stroke="#e7e9e2"/><text x={30} y={y(t)+4} textAnchor="end" className="chart-label">{Math.round(t*100)}%</text><text x={x(t)} y={248} textAnchor="middle" className="chart-label">{Math.round(t*100)}%</text></g>)}<path d={bins.map((p,i)=>`${i?'L':'M'}${x(p.predicted)},${y(p.observed)}`).join(' ')} fill="none" stroke="#b8735f" strokeWidth="2"/>{bins.map((p,i)=><circle key={i} cx={x(p.predicted)} cy={y(p.observed)} r={4} fill="#b8735f"/>)}<text x={210} y={266} textAnchor="middle" className="chart-label">Predicted probability</text></svg>}
